apiVersion: v1
kind: Namespace
metadata:
  name: namespace-c
  labels:
    role: frontend-c
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-c
  namespace: namespace-c
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    role: frontend-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-c
  namespace: namespace-c
spec:
  selector:
    matchLabels:
      role: frontend-c
  replicas: 1
  template:
    metadata:
      labels:
        role: frontend-c 
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: frontend-c
        ports:
        - containerPort: 80