apiVersion: v1
kind: Namespace
metadata:
  name: namespace-a
  labels:
    role: frontend-a
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-a
  namespace: namespace-a
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    role: frontend-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-a
  namespace: namespace-a
spec:
  selector:
    matchLabels:
      role: frontend-a
  replicas: 1
  template:
    metadata:
      labels:
        role: frontend-a 
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: frontend-a
        ports:
        - containerPort: 80