---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-role
  namespace: monitoring
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
      - pods
    verbs:
     # - create
      - get
      - list
     # - update
     # - delete
     # - watch
     # - patch  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-rolebinding
  namespace: monitoring
roleRef:
  apiGroup: ""
  kind: Role
  name: monitoring-role
subjects:
  - kind: User
    name: k8s-test-user
    apiGroup: ""

