---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-ainda
  namespace: "prod"
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-71f28429.efs.eu-central-1.amazonaws.com
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-ainda
  namespace: "prod"
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
