apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner-ainda
  namespace: "prod"
data:
  file.system.id: fs-71f28429
  aws.region: eu-central-1
  provisioner.name: example.com/aws-efs
  dns.name: "fs-71f28429.efs.eu-central-1.amazonaws.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-provisioner-ainda
  namespace: "prod"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: efs-provisioner-ainda
  namespace: "prod"
spec:
  selector:
    matchLabels:
      app: efs-provisioner-ainda
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner-ainda
    spec:
      containers:
        - name: efs-provisioner-ainda
          image: quay.io/external_storage/efs-provisioner:v0.1.0
          env:
            - name: FILE_SYSTEM_ID
              value: fs-71f28429
            - name: AWS_REGION
              value: eu-central-1
            - name: PROVISIONER_NAME
              value: example.com/aws-efs
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-71f28429.efs.eu-central-1.amazonaws.com
            path: /