apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: renantmagalhaes/skaffold-demo
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifests/k8s-deployment.yaml
