apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-Workshop
  region: eu-west-1
  version: "1.21"

iam:
    withOIDC: true

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.xlarge
    instancePrefix: EKS-WORKER
    instanceName: standard-workers
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 80
    volumeType: gp2
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
        cloudWatch: true
        autoScaler: true
        ebs: true
        efs: true

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
    
    # Sets the number of days to retain the logs for (see [CloudWatch docs](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#API_PutRetentionPolicy_RequestSyntax)).
    # By default, log data is stored in CloudWatch Logs indefinitely.
    logRetentionInDays: 60